name: IIB-ACE

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner (Ubuntu)

    steps:
      - uses: actions/checkout@v4

      - name: Run mqsiprofile command
        env:
          USERNAME: ${{ secrets.REMOTE_USER }}
          PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        run: |
          echo "Running IIB commands..."
          echo "$REMOTE_PASSWORD" | . /opt/ibm/mqsi/iib-10.0.0.7/server/bin/mqsiprofile
